spring.application.name=config-server
server.port=9998


spring.cloud.config.server.git.uri=https://github.com/qq57694878/springclouddemo/blob/master/static/SpringCloudConfig
spring.cloud.config.server.git.searchPaths=respo
spring.cloud.config.label=master
spring.cloud.config.server.git.username=qq57694878
spring.cloud.config.server.git.password=qq80447099