eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
server:
  port: 9998
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/qq57694878/springclouddemo
          searchPaths: static/SpringcloudConfig/respo
          username: qq57694878
          password: qq80447099

